#!/usr/bin/env python3
"""Generated single-file Render entrypoint."""

# Source: manim-test.py
# Generated by scripts/build_render_single_file.py
import asyncio
import contextlib
import logging
import shutil
import tempfile
import uuid
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, JSONResponse, PlainTextResponse
from pydantic import BaseModel, Field
from starlette.background import BackgroundTask

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

QUALITY_FLAGS = {
    "l": "-ql",
    "m": "-qm",
    "h": "-qh",
}

DEFAULT_QUALITY = "h"

JOBS: dict[str, dict] = {}
JOB_QUEUE: asyncio.Queue[str] = asyncio.Queue()

class RenderRequest(BaseModel):
    code: str
    scene_name: str = "MainScene"
    quality: str = Field(default=DEFAULT_QUALITY, pattern="^[lmh]$")


async def run_command(cmd: list[str], cwd: Path | None = None) -> tuple[int, str]:
    process = await asyncio.create_subprocess_exec(
        *cmd,
        cwd=str(cwd) if cwd else None,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.STDOUT,
    )

    output_chunks: list[str] = []
    assert process.stdout is not None

    while True:
        line = await process.stdout.readline()
        if not line:
            break
        decoded = line.decode(errors="replace")
        output_chunks.append(decoded)
        logger.info(decoded.rstrip())

    returncode = await process.wait()
    return returncode, "".join(output_chunks)


async def process_job(job_id: str) -> None:
    job = JOBS[job_id]
    job["status"] = "running"

    base = Path(tempfile.mkdtemp(prefix="manim_render_"))
    script = base / "scene.py"
    media = base / "media"
    compressed = base / "output.mp4"

    job["base_dir"] = str(base)

    try:
        media.mkdir(parents=True, exist_ok=True)
        script.write_text(job["code"], encoding="utf-8")

        manim_cmd = [
            "python",
            "-m",
            "manim",
            QUALITY_FLAGS[job["quality"]],
            str(script),
            job["scene_name"],
            "--media_dir",
            str(media),
            "--progress_bar",
            "none",
        ]
        manim_returncode, manim_output = await run_command(manim_cmd, cwd=base)
        job["logs"] += manim_output

        if manim_returncode != 0:
            job["status"] = "failed"
            job["error"] = "manim render failed"
            return

        mp4_files = list(media.rglob("*.mp4"))
        if not mp4_files:
            job["status"] = "failed"
            job["error"] = "render completed but no mp4 was produced"
            return

        video = mp4_files[0]
        ffmpeg_cmd = [
            "ffmpeg",
            "-y",
            "-i",
            str(video),
            "-vcodec",
            "libx264",
            "-crf",
            "18",
            "-preset",
            "slow",
            "-acodec",
            "aac",
            str(compressed),
        ]
        ffmpeg_returncode, ffmpeg_output = await run_command(ffmpeg_cmd, cwd=base)
        job["logs"] += ffmpeg_output

        final_video = compressed if ffmpeg_returncode == 0 and compressed.exists() else video
        if ffmpeg_returncode != 0:
            job["logs"] += "\nCompression failed, returning original render.\n"

        job["status"] = "done"
        job["video_path"] = str(final_video)
    except Exception as exc:
        logger.exception("job %s crashed", job_id)
        job["status"] = "failed"
        job["error"] = str(exc)


async def worker() -> None:
    while True:
        job_id = await JOB_QUEUE.get()
        try:
            await process_job(job_id)
        finally:
            JOB_QUEUE.task_done()


@asynccontextmanager
async def lifespan(_: FastAPI):
    task = asyncio.create_task(worker())
    try:
        yield
    finally:
        task.cancel()
        with contextlib.suppress(asyncio.CancelledError):
            await task


app = FastAPI(lifespan=lifespan)


def cleanup_job(job_id: str) -> None:
    job = JOBS.pop(job_id, None)
    if not job:
        return
    if job["base_dir"]:
        shutil.rmtree(job["base_dir"], ignore_errors=True)


@app.post("/jobs")
async def create_job(req: RenderRequest):
    job_id = str(uuid.uuid4())
    JOBS[job_id] = {
        "id": job_id,
        "status": "queued",
        "scene_name": req.scene_name,
        "quality": req.quality,
        "code": req.code,
        "logs": "",
        "error": None,
        "video_path": None,
        "base_dir": None,
    }
    await JOB_QUEUE.put(job_id)
    return {
        "job_id": job_id,
        "status": "queued",
        "quality": req.quality,
        "download_url": f"/jobs/{job_id}/download",
        "status_url": f"/jobs/{job_id}",
        "logs_url": f"/jobs/{job_id}/logs",
    }


@app.get("/jobs/{job_id}")
async def get_job(job_id: str):
    job = JOBS.get(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="job not found")

    position = None
    if job["status"] == "queued":
        queued_ids = list(JOB_QUEUE._queue)
        try:
            position = queued_ids.index(job_id) + 1
        except ValueError:
            position = None

    return {
        "job_id": job["id"],
        "status": job["status"],
        "scene_name": job["scene_name"],
        "quality": job["quality"],
        "error": job["error"],
        "queue_position": position,
        "ready": job["status"] == "done",
    }


@app.get("/jobs/{job_id}/logs")
async def get_logs(job_id: str):
    job = JOBS.get(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="job not found")
    return PlainTextResponse(job["logs"] or "")


@app.get("/jobs/{job_id}/download")
async def download_video(job_id: str):
    job = JOBS.get(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="job not found")
    if job["status"] == "failed":
        return JSONResponse(
            status_code=400,
            content={"error": job["error"] or "job failed", "logs": job["logs"]},
        )
    if job["status"] != "done" or not job["video_path"]:
        return JSONResponse(status_code=409, content={"status": job["status"]})

    return FileResponse(
        path=job["video_path"],
        media_type="video/mp4",
        filename=f"{job['scene_name']}.mp4",
        background=BackgroundTask(cleanup_job, job_id),
    )


@app.delete("/jobs/{job_id}")
async def delete_job(job_id: str):
    if job_id not in JOBS:
        raise HTTPException(status_code=404, detail="job not found")
    cleanup_job(job_id)
    return {"deleted": True, "job_id": job_id}

if __name__ == "__main__":
    import os
    import uvicorn

    host = os.environ.get("HOST", "0.0.0.0")
    port = int(os.environ.get("PORT", "8000"))
    uvicorn.run(app, host=host, port=port)
